apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: llmd-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.100.240-192.168.100.250  # Adjust to your free range
  autoAssign: true