apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - ../../operators/cert-manager
  # - ../../operators/leader-worker-set
  - ../../operators/rhoai
  - ../../operators/serverless
  - ../../operators/servicemeshoperator3/operator/overlays/stable
