apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/demos/overlays/nvidia-gpu-autoscale?ref=main
  # oc kustomize https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/demos/overlays/nvidia-gpu-autoscale?ref=main
  - setup.yaml
