apiVersion: v1
kind: Pod
metadata:
  name: guidellm
spec:
  containers:
  - name: guidellm
    image: ghcr.io/vllm-project/guidellm:v0.3.1
    command:
      - /bin/bash
      - -c
      - |
        #!/bin/sh

        debug(){
          echo "To infinity and beyond..."
          sleep infinity
        }

        debug
    resources:
      limits:
        cpu: '1'
        memory: 1Gi
      requests:
        cpu: '1'
        memory: 1Gi
    volumeMounts:
      - mountPath: /config
        name: empty
        subPath: config
      - mountPath: /results
        name: empty
  volumes:
    - name: empty
      emptyDir: {}
