apiVersion: v1
kind: Namespace
metadata:
  name: istio-cni
---
kind: IstioCNI
apiVersion: sailoperator.io/v1
metadata:
  name: default
spec:
  namespace: istio-cni
  version: v1.26.2
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
spec:
  namespace: istio-system
  updateStrategy:
    type: InPlace
    inactiveRevisionDeletionGracePeriodSeconds: 30
  version: v1.26.2
  values:
    pilot:
      env:
        # TO-DO: This need to be removed soon [istio issue](https://github.com/istio/istio/pull/57099)
        SUPPORT_GATEWAY_API_INFERENCE_EXTENSION: "true"
        ENABLE_GATEWAY_API_INFERENCE_EXTENSION: "true"