apiVersion: v1
kind: Pod
metadata:
  generateName: guidellm-
  # name: guidellm
spec:
  containers:
  - name: extended-resource-demo
    image: ghcr.io/vllm-project/guidellm:v0.3.0
    command:
      - /bin/bash
      - -c
      - |
        #!/bin/bash
        
        GUIDELLM_TARGET=http://llm-service:8000
        GUIDELLM_RATE_TYPE=sweep
        GUIDELLM_MAX_SECONDS=30
        GUIDELLM_DATA="prompt_tokens=256,output_tokens=128"

        guidellm benchmark run

        sleep infinity
